version: "3"
services:
  nodejs:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/User

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
